name: React CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Lint
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js đúng version (20.19.0)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm

      # 3. Cài dependencies
      - name: Install dependencies
        run: npm install

      # 4. Lint code
      - name: Lint
        run: npm run lint

      # 5. Build project
      - name: Build
        run: npm run build
